<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deployment"
    nsURI="deployment" nsPrefix="deployment">
  <eClassifiers xsi:type="ecore:EClass" name="DevelopmentEnvironment">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mediums" upperBound="-1"
        eType="#//Medium" containment="true" eOpposite="#//Medium/environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocols" upperBound="-1"
        eType="#//Protocol" containment="true" eOpposite="#//Protocol/environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="languages" upperBound="-1"
        eType="#//ProgrammingLanguage" containment="true" eOpposite="#//ProgrammingLanguage/environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" upperBound="-1" eType="#//OperatingSystem"
        containment="true" eOpposite="#//OperatingSystem/environment"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true" eOpposite="#//Connection/environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="devices" lowerBound="1"
        upperBound="-1" eType="#//Device" containment="true" eOpposite="#//Device/environment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true" eOpposite="#//Edge/environment"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Medium">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="technology" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/mediums"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Protocol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/protocols"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperatingSystem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/os"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProgrammingLanguage">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="profile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="revision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/languages"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platforms" lowerBound="1"
        upperBound="-1" eType="#//DevicePlatform" containment="true" eOpposite="#//DevicePlatform/device"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" lowerBound="1"
        upperBound="-1" eType="#//Entity" containment="true" eOpposite="#//Entity/device"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ongoing" upperBound="-1"
        eType="#//DeviceToConnectionEdge" eOpposite="#//DeviceToConnectionEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//ConnectionToDeviceEdge" eOpposite="#//ConnectionToDeviceEdge/target"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/devices"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platforms" lowerBound="1"
        upperBound="-1" eType="#//ConnectionPlatform" containment="true" eOpposite="#//ConnectionPlatform/connection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="information" lowerBound="1"
        upperBound="-1" eType="#//Information" containment="true" eOpposite="#//Information/connection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/connections"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ongoing" upperBound="-1"
        eType="#//ConnectionToDeviceEdge" eOpposite="#//ConnectionToDeviceEdge/source"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//DeviceToConnectionEdge" eOpposite="#//DeviceToConnectionEdge/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionPlatform" eSuperTypes="#//Platform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="1"
        eType="#//Connection" eOpposite="#//Connection/platforms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="protocol" lowerBound="1"
        eType="#//Protocol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="medium" lowerBound="1"
        eType="#//Medium"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DevicePlatform" eSuperTypes="#//Platform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/platforms"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="language" lowerBound="1"
        eType="#//ProgrammingLanguage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="os" eType="#//OperatingSystem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/entities"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Information">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="1"
        eType="#//Connection" eOpposite="#//Connection/information"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="environment" lowerBound="1"
        eType="#//DevelopmentEnvironment" eOpposite="#//DevelopmentEnvironment/edges"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceToConnectionEdge" eSuperTypes="#//Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/ongoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Connection" eOpposite="#//Connection/incoming"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConnectionToDeviceEdge" eSuperTypes="#//Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Connection" eOpposite="#//Connection/ongoing"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/incoming"/>
  </eClassifiers>
</ecore:EPackage>
